name: Docs

on:
  push:
    branches: [ master, doc-revamp ]

permissions:
  actions: read
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: windows-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      # Install DocFX
      - name: Setup DocFX
        run: dotnet tool update -g docfx
      
      # Build and publish docs
      - name: DocFX build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Upload assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4